### ISSUE TITLE
Does Roam  SDK - XCFramework version support new ARM based Mac?

### ISSUE THREAD

**Issue by jothipriyadharshanr** [roam-ai/roam-ios#13]
Description:

Hi, we integrated XCFramework version of Roam iOS SDK and it worked on an Intel CPU Macbook, however it didn't work on new ARM based Mac (M1) e.g. Mac Mini, Macbook Air, Macbook Pro. Are we missing anything while setting this up?

Environment:
1. Version: 0.0.6 XCFramework
2. Cocoapods

Steps to Reproduce Issue: NA
Anything else: NA

(crash stacktraces, as well as any other information here)

**Comment by ravikanth-tummala** [comment]
In order to support Apple M1 Macs, we need to add arm64 slice to our iOS simulator builds. This will not impact non M1 macs.
