### ISSUE TITLE
Crash creating user

### ISSUE THREAD

**Issue by magicwave** [roam-ai/roam-ios#2]
Unsuccessful getting data from the sdk. The following images illustrate our actions and crash console output. 

The call to `Roam.createUser( [user description])` always results in a crash (building on devices iPhone 7 and iPhone 10X). 

![initialization-image](https://user-images.githubusercontent.com/10930016/122874030-5fb66780-d2e7-11eb-84d7-fe37fee91f5b.png)
![create-user-image](https://user-images.githubusercontent.com/10930016/122874094-7361ce00-d2e7-11eb-9660-ee829ee1a883.png)
![console-image](https://user-images.githubusercontent.com/10930016/122874116-7957af00-d2e7-11eb-9f35-91a7dd87cfaa.png). 

The following is an iPhone 7 device crash log.   

[TestRoam  6-21-21, 7-50 PM.crash.txt](https://github.com/roam-ai/roam-ios/files/6691494/TestRoam.6-21-21.7-50.PM.crash.txt) (without symbolication of SDK selectors). 

<hr \>
The GeoSpark project playground shows a number of users, presumably created by multiple attempts to create a user in code, but the result of the call crashes. Also, attempts to save a userID from the Roam user object returned to the invocation closure fail.

Note that only invoking `Roam.initialize([production key])` and `Roam.setLogging(true)` results in console output, "GeoSpark initialized Success", without a crash, but with no functionality.
<img width="233" alt="initialize-success-console" src="https://user-images.githubusercontent.com/10930016/122840883-d46daf80-d2af-11eb-8e88-195394930664.png">

Also note that building to simulator IPhone 12 Pro always results in many undefined symbol errors, along with the warning:  
`Ignoring file /Users/eturner/Programming/Learning/TestRoam/Pods/roam-ios/Roam/Roam.framework/Roam, building for iOS Simulator-x86_64 but attempting to link with file built for iOS-arm64`

**Comment by jothipriyadharshanr** [comment]
Fixed in Release https://github.com/roam-ai/roam-ios/releases/tag/0.0.7
